### ISSUE TITLE
Deadlock on WebClient.ExecuteAsync

### ISSUE THREAD

**Issue by PeterHagen** [bnoffer/owncloud-sharp#10]
After testing the code from the CLI tool, I decided to try the code in a MVC website. When calling list(), I never got a response or exception. After debugging the code and searching some information I found a description of a deadlock on async which matched this issue. I change the method and got it working:

```
		/// <summary>
		/// Executes a HTTP reqquest async.
		/// </summary>
		/// <returns>HTTP Response.</returns>
		/// <param name="request">HTTP Request.</param>
		public  Task<HttpResponseMessage> ExecuteAsync(HttpRequestMessage request) {
			HttpClient client = new HttpClient (handler, false);
			client.Timeout = this.Timeout;

			return  client.SendAsync (request);
		}
```

With this change, the deadlock is gone. Maybe you can implement it

**Comment by bnoffer** [comment]
Thank you for this information, I had not used the library with ASP.Net. Another user already posted a fix for the WebDAVNet libarary here: https://github.com/bnoffer/webclient/pull/1

I will check both scenarios and see what works best.
