### ISSUE TITLE
SetUserAttribute results in Error 997 : failure

### ISSUE THREAD

**Issue by bnoffer** [bnoffer/owncloud-sharp#13]
ChrisHvd reached out to me via Twitter to report the following issue:

```
@bnoffer Tried ur great lib for owncloud! However, are u sure everythig works? Like, the SetUserAttribute? Got a 997 : failure. Any help?
```

If you read this issue, please supply more information (like ownCloud Version etc.), so I can try to reproduce the error.

**Comment by ChristopheHvd** [comment]
Hi Bastian,
I also reported the issue on the Owncloud github ([https://github.com/owncloud/core/issues/27976](https://github.com/owncloud/core/issues/27976).
I also discovered that the GroupExists(groupName) function does not work at all (returns true everytime).

Does it work properly on your side?

**Comment by bnoffer** [comment]
You should always mention which version of ownCloud you are using, which you did not in either of your posts.

Yes, you are correct there is an error in the GroupExists function. I'll create a new ticket for that.

Regarding the 997 error: According to the [External API Documentation](https://doc.owncloud.org/server/8.2/developer_manual/core/externalapi.html) the 997 error shows that you are not properly authenticated. Check the credentials that you are using to access ownCloud. It has to be a user with admin privileges.

**Comment by ChristopheHvd** [comment]
You are right for Owncloud version. Mine is OC 9.1.5. I'll mention it in my other post.
About the 997 error : I am using an admin account, that's the problem :(
But to be sure : I instantiate the OC Client with my admin credentials (login/password)
--> That will create the Authorization Basic token in the request header right?

Then I create a new user via your lib (that works apparently, even if, when I log the request via Fiddler, I can see a 403 authorization error request. But it works anyway), then I try to edit email/password/display of that user.
That's how I get the 997.

Does that work properly on your side?

**Comment by bnoffer** [comment]
Okay, I can verify the error occurs with ownCloud 8.2 as well. I am investigating the issue.

**Comment by bnoffer** [comment]
Found the solution: The problem is a mismatch between ownClouds user information output and the parameters the edituser call accepts.

The correct values for the **Key** value are all lower case:
```
    [0] => display
    [1] => quota
    [2] => password
    [3] => email
```
I found this described [here](https://forum.owncloud.org/viewtopic.php?t=26492).

Once I changed my key value from 'EMail' to email it worked.

**Comment by ChristopheHvd** [comment]
Tried the fix, seems to work, thanks!
However, in the Client.SetUserAttribute(), the returned bool is alway set to false, as the response.Data is alway null.
Also, there is an exception as you can see in the attached capture.
The exception message can be translated by "data not valid at root level"

**Comment by bnoffer** [comment]
Please update checked-out copy. While testing for your problem I fixed an issue regarding quota parsing. This is probably the cause for this issue.

I also updated the SetUserAttribute method to use a enum instead of a string, so these spelling errors do not occur anymore.

**Comment by ChristopheHvd** [comment]
Checked with your latest commit, I now have the enum type (well done) but still got a "false".
I try to execute and pass following test : 
`public static void Main (string[] args)
		{
			var c = new Client ("http://drive.bazimo.fr", "christophehvd", "cloudpourlesnoob");

            var username = "test2";

            if (!c.UserExists(username))
                c.CreateUser(username, "password");
            
            var flu = c.SetUserAttribute(username, OCSUserAttributeKey.EMail, "toto@toto.fr");
            var de = c.SetUserAttribute(username, OCSUserAttributeKey.Password, "popeye");
            var blu = c.SetUserAttribute(username, OCSUserAttributeKey.DisplayName, "Michel Toto");
            Console.WriteLine("Set email : " + flu);
            Console.WriteLine("Set password : " + de);
            Console.WriteLine("Set display : " + blu);

            var groupName = "myGroup";

            if (!c.GroupExists(groupName))
            {
                Console.WriteLine("Creating group " + groupName);
                c.CreateGroup(groupName);

            }
            if (c.GroupExists(groupName))
            {
                Console.WriteLine("adding user to group " + groupName);
                c.AddUserToGroup(username, groupName);
            }

            var directoryName = "myDirectory";
            if (!c.Exists("myDirectory"))
            {
                Console.WriteLine("Creating directory " + directoryName);
                c.CreateDirectory(directoryName);
            }

            Console.ReadKey();
		}`

**Comment by bnoffer** [comment]
Here is some sample code that works fine with 8.2:

```
var c = new Client ("http://my.server", "login", "password");
Console.WriteLine("Updating quota for user: test2");
var r3 = c.SetUserAttribute("test2", OCSUserAttributeKey.Quota, "101MB");
Console.WriteLine("Update result: " + r3);
var r2 = c.GetUserAttributes("test2");
Console.WriteLine("New quota: " + ((User)r2).Quota.Total);
```
The result looks like this:
![bildschirmfoto 2017-05-23 um 16 54 13](https://cloud.githubusercontent.com/assets/9718314/26360552/a9b6cdd0-3fd8-11e7-85c5-cfd9c966be86.png)

**Comment by ChristopheHvd** [comment]
mmm tried the same code, got false. Same for every attributes I try to set.
![capture](https://cloud.githubusercontent.com/assets/1823079/26361545/9ee247c4-3fdb-11e7-9c25-ad26e14aab82.JPG)

**Comment by bnoffer** [comment]
Okay, the only scenario where this can happen is if the response.Data object is null. You'll have to debug the parsing process to see where it crashes. Check your Visual Studio console output for any thrown exceptions.

**Comment by bnoffer** [comment]
This issue is really strange, because as far as I can see the OCS syntax has not changed. I'll have to setup a 9.1 test server to investigate this. Tomorrow is a holiday here, perhaps I'll find the time to do that.

**Comment by bnoffer** [comment]
Since the 997 error issue is resolved I close this issue and we continue the investigation on issue #17
