### ISSUE TITLE
GroupExists always returns true

### ISSUE THREAD

**Issue by bnoffer** [bnoffer/owncloud-sharp#14]
The proper result parsing is missing for the OCS result for group searches, therefore the GroupExists method used the StatusCode, which of course is always 100 if no other error occurs.

The response parsing for the OCS response needs to be updated and the GroupExists method has to be reworked to check the search results.

**Comment by ChristopheHvd** [comment]
Changed the method by following and tested successfully : 


            public bool GroupExists(string groupName)
        {
            var request = new RestRequest(GetOcsPath(ocsServiceCloud, "groups") + "?search={groupid}", Method.GET);
            request.AddHeader("OCS-APIREQUEST", "true");
            request.AddUrlSegment("groupid", groupName);

            var response = rest.Execute<OCS>(request);
            if (response.Data != null)
            {
                var groups = GetDataElements(response.Content);
                if (response.Data.Meta.StatusCode == 100)
                {
                    if (groups.Count > 0)
                        return true;
                }
                else
                    throw new OCSResponseError(response.Data.Meta.Message, response.Data.Meta.StatusCode + "");
            }

            return false;
        }`

**Comment by bnoffer** [comment]
I applied the same schema as for the UserExists method and therefore added a SearchGroups method that is called by GroupExists.
