### ISSUE TITLE
Solved! Show the files of cloud server on a WPF Window (exp. Label, TextBox or TextBlock)? 

### ISSUE THREAD

**Issue by carvinchen** [bnoffer/owncloud-sharp#20]
Hi, everyone

I am using this library to write a program as console application that shows the files of my owncloud server and it works well. I also would like to show them on TextBox or TextBlock of a WPF-Window, But it didnt / doesnt show anything and my WPF-Program was staying up (still running but not closed...). I have following lines to show:

`
        .
        .
        using owncloudsharp;
        using owncloudsharp.Types;
        .
        .
        .
        
        public string GetCurrentUser()
        {
            string currUsr;
            if (userConnected)
            {
                currUsr = currUsername + " is succesful logged in. ";
                UserTabContent.Content += "\nServer: " + currCloudUrl + " \nDatabase: " + currDatabase + "\nUser: "  + currUsername + "\n";
                var myClient = new Client(currCloudUrl, currUsername, currUserPW);
                
                ShowServerFiles(myClient, "");
            }
            else
            {
                MessageBox.Show("Connection is not ready, please sign in.");
                currUsr = "unbekannt";
            }
            return currUsr;
        }
        .
        .
        .
        private void userStatusUpdate_Loaded(object sender, RoutedEventArgs e) {
            UserLogStatus.Content = GetCurrentUser();
        }

        .
        .
        .
        public void ShowServerFiles(Client clientpc, string subPath)
        {
                var list = clientpc.List(subPath);
            
                UserTabContent.Content += "\n From the Path : " + subPath + " received " + list.Count + " item(s) \n";
        .
        .
        .
        }

`

Has anyone an idea to give me a solution to it? 

Cheers!

David

**Comment by bnoffer** [comment]
First declare the ownCloud# client globally in your class. It may be that by passing the instance through to another method there is data being lost. This is best practice anyway.

Then check if your server url and credentials are correct. If everything is setup properly it should work just fine.

**Comment by carvinchen** [comment]
Hi, bnoffer
Thank you for your answer! I tried your suggestion and change following lines of my code, but it still has the same problem..

Part of my code for my WPF-program:

`
     public partial class CloudTest : Window
     {
         
          //The following variables will be set when i click a button on another window. 
          public string currUsername = "";
          public string currUserPW = "";
          public string currCloudUrl = "";
          public string currDatabase = "";
          
          public Client myClient;
          
          public string GetCurrentUser()
          {
            string currUsr;
            if (userConnected)
            {
                currUsr = currUsername + " is erfolgreich eingeloggt. ";
            }
            else
            {
                MessageBox.Show("Connection is not ready, please sign in.");
                currUsr = "unbekannt";
            }
            return currUsr;
          }

          private void userStatusUpdate_Loaded(object sender, RoutedEventArgs e) {
              UserLogStatus.Content = GetCurrentUser();
          }
 
          //The Following function is going to show login data and list of files on server.
          public void UserTabContent_Loaded(object sender, RoutedEventArgs e) {

            if (userConnected)
            {
                UserTabContent.Content += "\nServer: " + currCloudUrl + " \nDatabase: " + currDatabase + "\nUser: " + currUsername + "\n";
                myClient = new Client(currCloudUrl, currUsername, currUserPW);
                var list = myClient.List("");

                //ShowServerFiles(myClient, "");
            }
            else
            {
                MessageBox.Show("Connection is not ready, please login again.");
            }
        }

        .
        .
        .

        public void ShowServerFiles(Client clientpc, string subPath)
        { 
           .
           . //It works in console application.
           .
        }

`
Any ideas? ;) Thank your very much!

David

**Comment by bnoffer** [comment]
I have not tried the library with WPF yet.

When debugging in Visual Studio, does the Output window contain messages in regards to exceptions? If so, please post them here.

**Comment by carvinchen** [comment]
Thanks!

If i break my program, i have seen that the WebClient.cs opened automatically and **showed me the line** 

`
                public HttpResponseMessage Execute(HttpRequestMessage request) {
			return ExecuteAsync (request).Result;
		}

`
will be exuted as the next, when the thread of another function has been finished.. 

**There are output messagers of debugging:**

`
"TestCloudConnector.vshost.exe" (CLR v4.0.30319: TestCloudConnector.vshost.exe): "C:\Windows\Microsoft.Net\assembly\GAC_32\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll" loaded. The loading of symbols was jumped over. The module is optimised, and the Debugoption "only own code" is activated.
"TestCloudConnector.vshost.exe" (CLR v4.0.30319: TestCloudConnector.vshost.exe): "C:\Windows\assembly\GAC_MSIL\Microsoft.VisualStudio.HostingProcess.Utilities\14.0.0.0__b03f5f7f11d50a3a\Microsoft.VisualStudio.HostingProcess.Utilities.dll" loaded. The loading of symbols was jumped over. The module is optimised, and the Debugoption "only own code" is activated.
"TestCloudConnector.vshost.exe" (CLR v4.0.30319: TestCloudConnector.vshost.exe): "C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll" loaded. The loading of symbols was jumped over. The module is optimised, and the Debugoption "only own code" is activated.
"TestCloudConnector.vshost.exe" (CLR v4.0.30319: TestCloudConnector.vshost.exe): "C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll" loaded. The loading of symbols was jumped over. The module is optimised, and the Debugoption "only own code" is activated.
"TestCloudConnector.vshost.exe" (CLR v4.0.30319: TestCloudConnector.vshost.exe): "C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll" loaded. The loading of symbols was jumped over. The module is optimised, and the Debugoption "only own code" is activated.
"TestCloudConnector.vshost.exe" (CLR v4.0.30319: TestCloudConnector.vshost.exe): "C:\Windows\assembly\GAC_MSIL\Microsoft.VisualStudio.HostingProcess.Utilities.Sync\14.0.0.0__b03f5f7f11d50a3a\Microsoft.VisualStudio.HostingProcess.Utilities.Sync.dll" loaded. The loading of symbols was jumped over. The module is optimised, and the Debugoption "only own code" is activated.
"TestCloudConnector.vshost.exe" (CLR v4.0.30319: TestCloudConnector.vshost.exe): "C:\Windows\assembly\GAC_MSIL\Microsoft.VisualStudio.Debugger.Runtime\14.0.0.0__b03f5f7f11d50a3a\Microsoft.VisualStudio.Debugger.Runtime.dll" loaded. The loading of symbols was jumped over. The module is optimised, and the Debugoption "only own code" is activated.
"TestCloudConnector.vshost.exe" (CLR v4.0.30319: TestCloudConnector.vshost.exe): "C:\Users\w.chen\Downloads\OwncloudLib\owncloud-sharp-master\TestCloudConnector\bin\Debug\TestCloudConnector.vshost.exe" loaded. The loading of symbols was jumped over. The module is optimised, and the Debugoption "only own code" is activated.
"TestCloudConnector.vshost.exe" (CLR v4.0.30319: TestCloudConnector.vshost.exe): "C:\Windows\Microsoft.Net\assembly\GAC_32\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll" loaded. The loading of symbols was jumped over. The module is optimised, and the Debugoption "only own code" is activated.
"TestCloudConnector.vshost.exe" (CLR v4.0.30319: TestCloudConnector.vshost.exe): "C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll" loaded. The loading of symbols was jumped over. The module is optimised, and the Debugoption "only own code" is activated.
"TestCloudConnector.vshost.exe" (CLR v4.0.30319: TestCloudConnector.vshost.exe): "C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll" loaded. The loading of symbols was jumped over. The module is optimised, and the Debugoption "only own code" is activated.
"TestCloudConnector.vshost.exe" (CLR v4.0.30319: TestCloudConnector.vshost.exe): "C:\Windows\Microsoft.Net\assembly\GAC_MSIL\Microsoft.CSharp\v4.0_4.0.0.0__b03f5f7f11d50a3a\Microsoft.CSharp.dll" loaded. The loading of symbols was jumped over. The module is optimised, and the Debugoption "only own code" is activated.
"TestCloudConnector.vshost.exe" (CLR v4.0.30319: TestCloudConnector.vshost.exe): "C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml.Linq\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.Linq.dll" loaded. The loading of symbols was jumped over. The module is optimised, and the Debugoption "only own code" is activated.
"TestCloudConnector.vshost.exe" (CLR v4.0.30319: TestCloudConnector.vshost.exe): "C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Data.DataSetExtensions\v4.0_4.0.0.0__b77a5c561934e089\System.Data.DataSetExtensions.dll" loaded. The loading of symbols was jumped over. The module is optimised, and the Debugoption "only own code" is activated.
"TestCloudConnector.vshost.exe" (CLR v4.0.30319: TestCloudConnector.vshost.exe): "C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Net.Http\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Net.Http.dll" loaded. The loading of symbols was jumped over. The module is optimised, and the Debugoption "only own code" is activated.
"TestCloudConnector.vshost.exe" (CLR v4.0.30319: TestCloudConnector.vshost.exe): "C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xaml\v4.0_4.0.0.0__b77a5c561934e089\System.Xaml.dll" loaded. The loading of symbols was jumped over. The module is optimised, and the Debugoption "only own code" is activated.
"TestCloudConnector.vshost.exe" (CLR v4.0.30319: TestCloudConnector.vshost.exe): "C:\Windows\Microsoft.Net\assembly\GAC_MSIL\WindowsBase\v4.0_4.0.0.0__31bf3856ad364e35\WindowsBase.dll" loaded. The loading of symbols was jumped over. The module is optimised, and the Debugoption "only own code" is activated.
"TestCloudConnector.vshost.exe" (CLR v4.0.30319: TestCloudConnector.vshost.exe): "C:\Windows\Microsoft.Net\assembly\GAC_32\PresentationCore\v4.0_4.0.0.0__31bf3856ad364e35\PresentationCore.dll" loaded. The loading of symbols was jumped over. The module is optimised, and the Debugoption "only own code" is activated.
"TestCloudConnector.vshost.exe" (CLR v4.0.30319: TestCloudConnector.vshost.exe): "C:\Windows\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.dll" loaded. The loading of symbols was jumped over. The module is optimised, and the Debugoption "only own code" is activated.
The Thread 0x2ea0has ended with code 0 (0x0).
The Thread 0x5a84has ended with code 0 (0x0).
"TestCloudConnector.vshost.exe" (CLR v4.0.30319: TestCloudConnector.vshost.exe): "C:\Users\w.chen\Downloads\OwncloudLib\owncloud-sharp-master\TestCloudConnector\bin\Debug\TestCloudConnector.exe" loaded. Symbols were loaded.
Einzelschritt: Nichtbenutzercode "TestCloudConnector.App..ctor" wird übersprungen.
"TestCloudConnector.vshost.exe" (CLR v4.0.30319: TestCloudConnector.vshost.exe): "C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll" loaded. The loading of symbols was jumped over. The module is optimised, and the Debugoption "only own code" is activated.
Einzelschritt: Nichtbenutzercode "TestCloudConnector.App.InitializeComponent" wird übersprungen.
"TestCloudConnector.vshost.exe" (CLR v4.0.30319: TestCloudConnector.vshost.exe): "C:\Windows\Microsoft.Net\assembly\GAC_MSIL\mscorlib.resources\v4.0_4.0.0.0_de_b77a5c561934e089\mscorlib.resources.dll" loaded. The module was provided without symbols.
"TestCloudConnector.vshost.exe" (CLR v4.0.30319: TestCloudConnector.vshost.exe): "C:\Windows\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework.Aero2\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.Aero2.dll" loaded. The loading of symbols was jumped over. The module is optimised, and the Debugoption "only own code" is activated.
"TestCloudConnector.vshost.exe" (CLR v4.0.30319: TestCloudConnector.vshost.exe): "C:\Windows\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework.resources\v4.0_4.0.0.0_de_31bf3856ad364e35\PresentationFramework.resources.dll" loaded. The module was provided without symbols.
"TestCloudConnector.vshost.exe" (CLR v4.0.30319: TestCloudConnector.vshost.exe): "C:\Windows\Microsoft.Net\assembly\GAC_MSIL\PresentationCore.resources\v4.0_4.0.0.0_de_31bf3856ad364e35\PresentationCore.resources.dll" loaded. The module was provided without symbols.
"TestCloudConnector.vshost.exe" (CLR v4.0.30319: TestCloudConnector.vshost.exe): "C:\Windows\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework-SystemXmlLinq\v4.0_4.0.0.0__b77a5c561934e089\PresentationFramework-SystemXmlLinq.dll" loaded. The loading of symbols was jumped over. The module is optimised, and the Debugoption "only own code" is activated.
"TestCloudConnector.vshost.exe" (CLR v4.0.30319: TestCloudConnector.vshost.exe): "C:\Windows\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework-SystemXml\v4.0_4.0.0.0__b77a5c561934e089\PresentationFramework-SystemXml.dll" loaded. The loading of symbols was jumped over. The module is optimised, and the Debugoption "only own code" is activated.
"TestCloudConnector.vshost.exe" (CLR v4.0.30319: TestCloudConnector.vshost.exe): "C:\Users\WDC13~1.CHE\AppData\Local\Temp\VisualStudio.XamlDiagnostics.15164\WpfXamlDiagnosticsTap.dll" loaded. The loading of symbols was jumped over. The module is optimised, and the Debugoption "only own code" is activated.
"TestCloudConnector.vshost.exe" (CLR v4.0.30319: TestCloudConnector.vshost.exe): "C:\Windows\assembly\GAC\Microsoft.VisualStudio.OLE.Interop\7.1.40304.0__b03f5f7f11d50a3a\Microsoft.VisualStudio.OLE.Interop.dll" loaded. The loading of symbols was jumped over. The module is optimised, and the Debugoption "only own code" is activated.
"TestCloudConnector.vshost.exe" (CLR v4.0.30319: TestCloudConnector.vshost.exe): "C:\Windows\Microsoft.Net\assembly\GAC_MSIL\UIAutomationTypes\v4.0_4.0.0.0__31bf3856ad364e35\UIAutomationTypes.dll" loaded. The loading of symbols was jumped over. The module is optimised, and the Debugoption "only own code" is activated.
"TestCloudConnector.vshost.exe" (CLR v4.0.30319: TestCloudConnector.vshost.exe): "C:\Windows\Microsoft.Net\assembly\GAC_MSIL\Accessibility\v4.0_4.0.0.0__b03f5f7f11d50a3a\Accessibility.dll" loaded. PDB file was not found or could not be opened.
"TestCloudConnector.vshost.exe" (CLR v4.0.30319: TestCloudConnector.vshost.exe): "C:\Windows\Microsoft.Net\assembly\GAC_MSIL\UIAutomationProvider\v4.0_4.0.0.0__31bf3856ad364e35\UIAutomationProvider.dll" loaded. The loading of symbols was jumped over. The module is optimised, and the Debugoption "only own code" is activated.
"TestCloudConnector.vshost.exe" (CLR v4.0.30319: TestCloudConnector.vshost.exe): "C:\Users\w.chen\Downloads\OwncloudLib\owncloud-sharp-master\TestCloudConnector\bin\Debug\owncloud-sharp.dll" loaded. Symbols were loaded.
"TestCloudConnector.vshost.exe" (CLR v4.0.30319: TestCloudConnector.vshost.exe): "C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Runtime\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.dll" loaded. The loading of symbols was jumped over. The module is optimised, and the Debugoption "only own code" is activated.
"TestCloudConnector.vshost.exe" (CLR v4.0.30319: TestCloudConnector.vshost.exe): "C:\Users\w.chen\Downloads\OwncloudLib\owncloud-sharp-master\TestCloudConnector\bin\Debug\RestSharp.dll" loaded. PDB file was not found or could not be opened.
"TestCloudConnector.vshost.exe" (CLR v4.0.30319: TestCloudConnector.vshost.exe): "C:\Users\w.chen\Downloads\OwncloudLib\owncloud-sharp-master\TestCloudConnector\bin\Debug\webdavnet.dll" loaded. Symbols were loaded.
"TestCloudConnector.vshost.exe" (CLR v4.0.30319: TestCloudConnector.vshost.exe): "C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Net.Primitives\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Net.Primitives.dll" loaded. The module was provided without symbols.
"TestCloudConnector.vshost.exe" (CLR v4.0.30319: TestCloudConnector.vshost.exe): "C:\Users\w.chen\Downloads\OwncloudLib\owncloud-sharp-master\TestCloudConnector\bin\Debug\WebClient.dll" loaded. Symbols were loaded.
"TestCloudConnector.vshost.exe" (CLR v4.0.30319: TestCloudConnector.vshost.exe): "C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Collections\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Collections.dll" loaded. The loading of symbols was jumped over. The module is optimised, and the Debugoption "only own code" is activated.
"TestCloudConnector.vshost.exe" (CLR v4.0.30319: TestCloudConnector.vshost.exe): "C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Threading.Tasks\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Threading.Tasks.dll" loaded. The loading of symbols was jumped over. The module is optimised, and the Debugoption "only own code" is activated.
"TestCloudConnector.vshost.exe" (CLR v4.0.30319: TestCloudConnector.vshost.exe): "C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.IO\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.IO.dll" loaded. The loading of symbols was jumped over. The module is optimised, and the Debugoption "only own code" is activated.
"TestCloudConnector.vshost.exe" (CLR v4.0.30319: TestCloudConnector.vshost.exe): "C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Extensions\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.Extensions.dll" loaded. The loading of symbols was jumped over. The module is optimised, and the Debugoption "only own code" is activated.
"TestCloudConnector.vshost.exe" (CLR v4.0.30319: TestCloudConnector.vshost.exe): "C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Diagnostics.Debug\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Diagnostics.Debug.dll" loaded. The loading of symbols was jumped over. The module is optimised, and the Debugoption "only own code" is activated.
"TestCloudConnector.vshost.exe" (CLR v4.0.30319: TestCloudConnector.vshost.exe): "C:\Users\w.chen\Downloads\OwncloudLib\owncloud-sharp-master\TestCloudConnector\bin\Debug\System.Net.Http.Primitives.dll" loaded. The loading of symbols was jumped over. The module is optimised, and the Debugoption "only own code" is activated.
The Thread 0x39bc has ended with code 0 (0x0).
The Thread 0x49f0has ended with code 0 (0x0).
"TestCloudConnector.vshost.exe" (CLR v4.0.30319: TestCloudConnector.vshost.exe): "C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.resources\v4.0_4.0.0.0_de_b77a5c561934e089\System.resources.dll" loaded. The module was provided without symbols.
"TestCloudConnector.vshost.exe" (CLR v4.0.30319: TestCloudConnector.vshost.exe): "C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Net.Http.resources\v4.0_4.0.0.0_de_b03f5f7f11d50a3a\System.Net.Http.resources.dll" loaded. The module was provided without symbols.
The Thread 0x5688has ended with code 0 (0x0).


`

Could your give me any suggestions about it? 

Cheers!

David

**Comment by carvinchen** [comment]
Hi, bnoffer

Thanks for your answer and new link! It helped me to understand it better, but i still have aquestion:

How should i do i t better, if i want to make a login window (Window A) and a file window (Window B) that shows me folders and files on server? 

I have tried to do it by creating a Textblock_loaded function. In the function i create the Client with the parameters (serverUrl, user, passwd) i got from Window A  and it shows me on the file window : Connected! User has 0 files and folders in his home directory... 

But if i create a button for connection on Window B and put the Lines in there, it works well and shows me correct nummers...

Would you like to show me a example related to my problem, if you have time?

Thank you very much!

David

**Comment by bnoffer** [comment]
If possible zip your code and attach it here, then I can download, review and test it.

**Comment by carvinchen** [comment]
Thank you, bnoffer for the new update of this project and it works fine with it. LG, David

**Comment by bnoffer** [comment]
Nice to hear that you got it working. I am therefore closing this issue.
