### ISSUE TITLE
Solved! Problem with Client.Download ?

### ISSUE THREAD

**Issue by carvinchen** [bnoffer/owncloud-sharp#25]
Hi, bnoffer

I have tested this function Client.Download("myurl/filename") before and it worked well. 

But i am watching back the function now and it gives me the incorrect length of the file i wanted to download from the server. It is the same result: File found with size: 7607 Bytes received. 

And i have the new local file with size: 7 kb...  Do Your have any ideas? 

The main part of my code:

`
           string rootFolderOwncloud = "http://myip/owncloud/";
.
.
.
           var fileToDown = myClient.Download(rootFolderOwncloud + 
           "/myfolder/test.pdf");
                     if (fileToDown.Length > 0)
                     {
                         Console.Write("\nFile found with size: " + fileToDown.Length.ToString() + " Bytes received. \n");
                         BinaryReader reader = new BinaryReader(fileToDown);
                         fileToDown.Position = 0;
                         byte[] rdata = reader.ReadBytes((int)fileToDown.Length);
                         File.WriteAllBytes(pathToSave + "localDoc.pdf", rdata);

                     }else{
                         Console.Write("\nNOO File found... \n");
                     }
.
.
.

`

Cheers!

David

**Comment by carvinchen** [comment]
Sorry, this question should be closed, i just have taken a wrong parameter of the function Download..It works fine! Cheers.

**Comment by bnoffer** [comment]
No problem, I am glad to hear that it works. Closing this issue now.
