### ISSUE TITLE
Question to set password to a user from passwordbox?

### ISSUE THREAD

**Issue by carvinchen** [bnoffer/owncloud-sharp#26]
Hi, all

I want to get the password by using passwordbox.password and set it to a user by using myClient.SetUserAttribute(newUser, OCSUserAttributeKey.Password, passwordbox.password), it seems like to work. But if i log in with new password, i showed me wrong password...

2. Question: how could i get the password of an user?

Has anyone ideas about this problem?

Thanks!

David

**Comment by bnoffer** [comment]
The call itself should work properly. I am remembering an issue with the ASP.Net Password control where you were unable to properly read the control. Perhaps check if you get the correct password out of the control before sending it to the server. In the ASP.Net case I had to use a work around using manual masking of a normal textbox.

**Comment by carvinchen** [comment]
Thank you for your answer! Would you like to try a simple program in WPF? Maybe you will get the same problem...

**Comment by bnoffer** [comment]
You can not get the password of a user via the library, you can only set it. This is due to ownCloud only storing hashes of the password, so the password can not be guessed if the database is vulnerable to attacks.

I tested setting passwords using that method and it worked just fine. Not in WPF, but this does not matter at this point, because the error related to the other issue was part of the WebDAV calls and that had been fixed as well.

**Comment by carvinchen** [comment]
Could you post me a link to the issue of the WebDav that has been fixed? Thank you!

**Comment by bnoffer** [comment]
The issue you had, that I am referring to, was #20 , the original issue was #10

**Comment by carvinchen** [comment]
Hi, bnoffer

I think the reason is SetUserAttribute(newUser, OCSUserAttributeKey.EMail, userEmail)...would you like to test the function again on your pc? Must i change anything in Client.cs? 

Thank you!

LG, david

**Comment by bnoffer** [comment]
There was an issue with the `OCSUserAttributeKey` enum values, but this has been fixed as of commit bbb3e9d2a06bb64bc830723900bc5300d1402b64

If you are running the latest code base, there should not be a problem.

**Comment by carvinchen** [comment]
Thank you!

Accucially i have seen the same nummer 2 before of the enum OCSUserAttributeKey, but for some reason i didnt correct it by me first...i remember that.. 

The function SetUserAttribute(newUser, OCSUserAttributeKey.EMail, userEmail) works, but if i want get the saved email of the user and have another problem as following:

`
                curUser = cloudClient.GetUserAttributes(cloudUsername);
                cloudEmail = curUser.EMail;
                Console.WriteLine("\n Cur Email: " + cloudEmail + ". \n");

`
If i run it it didnt show me any email i saved for the user by using SetUserAttribute(...), and if i run it in WPF, i got the error:  https://img5.picload.org/image/riidgcdr/error_quota.png

But without the 3 lines above i didnt get any error, it has nothing to do with "Quota" or was do you think?

Cheers, David

**Comment by bnoffer** [comment]
Just checked with ownCloud 9.1, I ran the following code:
```
var r1 = c.CreateUser("demo001", "D8!di7As1");
Console.WriteLine(r1);
var r2 = c.SetUserAttribute("demo001", OCSUserAttributeKey.EMail, "demo001@example.com");
Console.WriteLine(r2);
var r3 = c.GetUserAttributes("demo001");
Console.WriteLine(r3.EMail);
```
Result:
![bildschirmfoto 2017-06-09 um 14 53 00](https://user-images.githubusercontent.com/9718314/26976337-ae97b2b2-4d23-11e7-9722-468d4c6db831.png)
Therefore I can not confirm your issue.

And I tested setting that users password via:
```
var r1 = c.SetUserAttribute("demo001", OCSUserAttributeKey.Password , "D8!di7Ab9");
```
and it worked. I logged in before that with the old password and afterwards with the new.

**Comment by bnoffer** [comment]
Question seems to be answered, I am therefore closing this issue.
