### ISSUE TITLE
Nuget package?

### ISSUE THREAD

**Issue by elpatron68** [bnoffer/owncloud-sharp#29]
Hi,
First of all: Thanks, this helped me a lot.
I found it quite hard to build this project. Would it be possible to publish the binaries as Nuget package?

Best regards,
Markus

**Comment by bnoffer** [comment]
Creating a Nuget package was not yet on the roadmap, but I will look into it.

**Comment by bnoffer** [comment]
Okay, a Nuget Package has been made available here:
https://www.nuget.org/packages/bnoffer.owncloudsharp/

**Comment by elpatron68** [comment]
Great, thanks a lot!

**Comment by bnoffer** [comment]
Added the NuGet details to [the Wiki](https://github.com/bnoffer/owncloud-sharp/wiki).
