### ISSUE TITLE
Can#t get Client.Download to work properly

### ISSUE THREAD

**Issue by t1h8li** [bnoffer/owncloud-sharp#30]
Hi there,
Hooked up the sample app to our owncloud instance.
Directory listing and folder creation are working just fine.
But Downloading of content just gets 29KB of data regardless the size of the file.
What am i doing wrong ?
Any tipps / help highly appreciated. I am using V0.3.0

Best regards,

Marc

**Comment by bnoffer** [comment]
In order to investigate I need to know which version of ownCloud/NextCloud you are using.

**Comment by t1h8li** [comment]
Hi Bastian,
quite embarassing, but we are still on 8.0 ...
Upload of files and sharing wtih LINK are working flawlessly.

**Comment by bnoffer** [comment]
Does your webservers log or the ownCloud log show any errors?

**Comment by t1h8li** [comment]
Nope, no errors whatsoever …

Von: Bastian Noffer [mailto:notifications@github.com]
Gesendet: Dienstag, 25. Juli 2017 09:55
An: bnoffer/owncloud-sharp <owncloud-sharp@noreply.github.com>
Cc: Linde, Marc <Linde@kdo.de>; Author <author@noreply.github.com>
Betreff: Re: [bnoffer/owncloud-sharp] Can#t get Client.Download to work properly (#30)


Does your webservers log or the ownCloud log show any errors?

**Comment by bnoffer** [comment]
Currently I have only a 8.1 test installation and there it works just fine, here is the sample code:

```
var ri = c.GetResourceInfo("/ownCloudUserManual.pdf");
var ds = c.Download("/ownCloudUserManual.pdf");
using (var f = File.Open("ownCloudUserManual.pdf", FileMode.Create)) {
    ds.Seek(0, SeekOrigin.Begin);
    ds.CopyTo(f);
    Console.WriteLine("Size expected: " + ri.Size + "  Size downloaded: " + f.Length);
}
```

File sizes reported by the ResourceInfo and the downloaded file match and the file opens properly.

**Comment by t1h8li** [comment]
Hi Bastian,

i really apreciate you efforts – thanks a lot.
Consider this issue solved.
At the moment the current usecase only affects upload and sharing of ressources.
Will test your provided source later.

Kind regards,

Marc

Von: Bastian Noffer [mailto:notifications@github.com]
Gesendet: Mittwoch, 26. Juli 2017 10:50
An: bnoffer/owncloud-sharp <owncloud-sharp@noreply.github.com>
Cc: Linde, Marc <Linde@kdo.de>; Author <author@noreply.github.com>
Betreff: Re: [bnoffer/owncloud-sharp] Can#t get Client.Download to work properly (#30)


Currently I have only a 8.1 test installation and there it works just fine, here is the sample code:

var ri = c.GetResourceInfo("/ownCloudUserManual.pdf");

var ds = c.Download("/ownCloudUserManual.pdf");

using (var f = File.Open("ownCloudUserManual.pdf", FileMode.Create)) {

    ds.Seek(0, SeekOrigin.Begin);

    ds.CopyTo(f);

    Console.WriteLine("Size expected: " + ri.Size + "  Size downloaded: " + f.Length);

}

File sizes reported by the ResourceInfo and the downloaded file match and the file opens properly.
