### ISSUE TITLE
[ANNOUNCEMENT] ownCloud# v2.0 with .NET Core/.NET Standard support

### ISSUE THREAD

**Issue by bnoffer** [bnoffer/owncloud-sharp#48]
Hi everyone,

I finally got time to start working on the port and updating of the library for .NET Core/.NET Standard support. The initial basics are done, now comes the busy work. Expect further updates in the upcoming weeks.

In the process I also updated the WebDAVNet and WebClient projects, they both got a `develop` branch that can be still quite messy. Once I get a more complete state of the whole project I will clean-up properly. Same goes for the `devel` branch of this main project.

In case of questions / comments feel free to leave a comment below.

Regards,
Bastian

**Comment by Yogeswaran66** [comment]
Hi. When can we expect the library to be compatible with  .NET Core

**Comment by bnoffer** [comment]
I am sorry @Yogeswaran66 , but I have to declare the project as unmaintained for now. Please see #49 for details.
