### ISSUE TITLE
where to get RestSharp for .NET 3.5

### ISSUE THREAD

**Issue by squadwuschel** [bnoffer/owncloud-sharp#9]
where can I get the RestSharp for .NET 3.5 dlls and is ther ea NuGet somewhere for your client dlls

**Comment by bnoffer** [comment]
Sorry for the late response.

You need to build it yourself. RestSharp can be obtained from the projects GitHub here:
https://github.com/restsharp/RestSharp
To my knowledge the primary project "RestSharp" in the solution is the one targeting .Net 3.5.

I attached my build from RestSharp 105.2.3.
[RestSharp.zip](https://github.com/bnoffer/owncloud-sharp/files/527037/RestSharp.zip)

**Comment by bnoffer** [comment]
I moved this answer to the [Wiki](https://github.com/bnoffer/owncloud-sharp/wiki)

**Comment by funky81** [comment]
> Sorry for the late response.
> 
> You need to build it yourself. RestSharp can be obtained from the projects GitHub here:
> https://github.com/restsharp/RestSharp
> To my knowledge the primary project "RestSharp" in the solution is the one targeting .Net 3.5.
> 
> I attached my build from RestSharp 105.2.3.
> [RestSharp.zip](https://github.com/bnoffer/owncloud-sharp/files/527037/RestSharp.zip)

Thanks a lot for this...you're my life saviour

**Comment by rhysstubbs** [comment]
> Sorry for the late response.
> 
> You need to build it yourself. RestSharp can be obtained from the projects GitHub here:
> https://github.com/restsharp/RestSharp
> To my knowledge the primary project "RestSharp" in the solution is the one targeting .Net 3.5.
> 
> I attached my build from RestSharp 105.2.3.
> [RestSharp.zip](https://github.com/bnoffer/owncloud-sharp/files/527037/RestSharp.zip)

I had just written an API client targeting .NET standard 2.0, obviously forgetting the project that will reference it is only .NET framework 3.5. Thank you!! Sad times, no scope to upgrade :(

**Comment by pratikjain1980** [comment]
many many thanks for the dll
